### ISSUE TITLE
v2.1/rentals returns always 0€ cost

### ISSUE THREAD

**Issue by njoylab** [car2go/openAPI#13]
Every trip has 0 amount

ex:
usageAmount = {
                amountGross = 0;
                amountNet = 0;
                amountVat = 0;
                currency = EUR;
};

**Comment by guggens** [comment]
Hi, we fixed the bug in production, thanks for the report. Can you confirm that?
If you have further problems, please tell us the user account which was used to access the openAPI

Regards, Sascha

**Comment by njoylab** [comment]
Hi!
Yes I confirm it's fixed now.

Thanks!
